### PR TITLE
Csv download

### PR DESCRIPTION
**Pull request by abhisuri97**
@riyer15 and my changes for csv/search page stuff.

Removed need to query dom for grabbing info, now keeping 2 sources of information (1 displayed on the DOM and the second that is just an object  storing all of the  org information from the beginning). 

CSV now contains the following columns:

name | description | email | phone | address | website | hours | services | tags
-- | -- | -- | -- | -- | -- | -- | -- | --

### CODE REVIEW

**Comment by stevenbursztyn** [comment]
@abhisuri97 any way to still show results in alphabetical order but still get it to work? If not, can we merge this in?

**Comment by riyer15** [comment]
@stevenbursztyn is your comment resolved?

**Comment by stevenbursztyn** [comment]
yea, to fix CSV download my change isnt possible. Not an issue tho tbh

**Comment by riyer15** [comment]
ok, lgtm then

**Pull request merged**
