### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by abhisuri97**
Merge in after #26 . 

_Most_ responsive issues fixed that i could find...if time permits, we need to overhaul the table logic in the search results to just have divs.

### CODE REVIEW

**Comment by stevenbursztyn** [comment]
This is messing w the footer a little bit (the logo section & text wrapping) and the pictures in search are no longer being displayed as big squares like they were before

**Comment by abhisuri97** [comment]
@stevenbursztyn not sure about the logo issues you're seeing, could you post a screencap?
image

mobile:
image

(only change on this is mobile b/c it doesn't make sense to keep a huge logo at the bottom as a footer, so i just scale it down)

Also for search, do you want height limited to 200px? i wasn't sure if that was meant  to be put in or not

**Comment by stevenbursztyn** [comment]
@abhisuri97 More or less what the footer should look like (as it does now on web):
screen shot 2018-05-20 at 7 57 05 pm


What the footer looks like in this PR (logo is in a weird position, and i guess text alignment also off but thats an easier fix):
screen shot 2018-05-20 at 7 59 11 pm


===========
Regarding search, this is what it should still look like:
screen shot 2018-05-20 at 8 00 59 pm

but it's looking like this instead:
screen shot 2018-05-20 at 7 59 46 pm

**Comment by abhisuri97** [comment]
image
I'm getting a  very weird misalign on the top at desktop size which is why i chose to just align to bottom right

I think i fixed search. issue is  that i've made search responsive so it isn't constrained to a table anymore, so enforcing an image size on it is a bit weird (typically you go by percentage values).

**Review by stevenbursztyn — APPROVED** [review]

**Review by riyer15 — APPROVED** [review]

**Pull request merged**
